services: 

  mongo: 
    command: "--nojournal"
    container_name: mongo
    image: "mongo:3.4"

  orion: 
    command: "-dbhost mongo"
    container_name: orion
    hostname: orion
    image: fiware/orion
    links: 
      - mongo
    ports: 
      - "1026:1026"

      
version: "3"
